/*
    Assurance Horizon portfolio quote schema
    Target database: PostgreSQL 16+

    This script is mounted by docker-compose.yml into /docker-entrypoint-initdb.d.
    The Compose database uses tmpfs storage for demo resets, so it runs whenever
    the Postgres container starts with an empty data directory.
    It is intentionally idempotent enough to be reused by local setup scripts and
    Testcontainers initialization.
*/

CREATE SCHEMA IF NOT EXISTS quote;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS quote.gender_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    display_text varchar(100) NOT NULL,
    display_text_en varchar(100),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.marital_status_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    display_text varchar(100) NOT NULL,
    display_text_en varchar(100),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.education_level_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    display_text varchar(150) NOT NULL,
    display_text_en varchar(150),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.yes_no_unknown_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    display_text varchar(100) NOT NULL,
    display_text_en varchar(100),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.purchase_condition_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code varchar(50) NOT NULL UNIQUE,
    display_text varchar(100) NOT NULL,
    display_text_en varchar(100),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.month_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_number integer NOT NULL UNIQUE CHECK (month_number BETWEEN 1 AND 12),
    code char(2) NOT NULL UNIQUE,
    display_text varchar(30) NOT NULL,
    display_text_en varchar(30) NOT NULL,
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.vehicle_manufacturers
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100) NOT NULL UNIQUE,
    is_active boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS quote.vehicle_models
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manufacturer_id integer NOT NULL REFERENCES quote.vehicle_manufacturers(id),
    model_year integer NOT NULL CHECK (model_year BETWEEN 1980 AND 2100),
    model_name varchar(100) NOT NULL,
    trim varchar(150),
    vehicle_code varchar(50),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_vehicle_models_model UNIQUE NULLS NOT DISTINCT
        (manufacturer_id, model_year, model_name, trim)
);

CREATE TABLE IF NOT EXISTS quote.distance_options
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kilometers integer NOT NULL CHECK (kilometers >= 0),
    display_text varchar(50) NOT NULL,
    display_text_en varchar(50),
    option_type varchar(50) NOT NULL CHECK (option_type IN ('CurrentOdometer', 'AnnualDistance')),
    sort_order integer NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT uq_distance_options_value UNIQUE (kilometers, option_type)
);

CREATE TABLE IF NOT EXISTS quote.quotes
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    product_type varchar(50) NOT NULL CHECK (product_type IN ('Auto')),
    status varchar(50) NOT NULL CHECK (status IN ('Draft', 'Submitted', 'Quoted', 'Abandoned')),
    current_step varchar(50),
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote.quote_drivers
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_id uuid NOT NULL REFERENCES quote.quotes(id) ON DELETE CASCADE,
    driver_role varchar(50) NOT NULL CHECK (driver_role IN ('Primary', 'Additional')),
    first_name varchar(100) NOT NULL,
    last_name varchar(100) NOT NULL,
    birth_year integer CHECK (birth_year IS NULL OR birth_year BETWEEN 1900 AND 2100),
    birth_month integer CHECK (birth_month IS NULL OR birth_month BETWEEN 1 AND 12),
    email varchar(254),
    cellphone varchar(30),
    gender_id integer REFERENCES quote.gender_options(id),
    marital_status_id integer REFERENCES quote.marital_status_options(id),
    education_level_id integer REFERENCES quote.education_level_options(id),
    is_full_time_student boolean,
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote.quote_vehicles
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_id uuid NOT NULL REFERENCES quote.quotes(id) ON DELETE CASCADE,
    model_year integer CHECK (model_year IS NULL OR model_year BETWEEN 1980 AND 2100),
    manufacturer_id integer REFERENCES quote.vehicle_manufacturers(id),
    vehicle_model_id integer REFERENCES quote.vehicle_models(id),
    vehicle_code varchar(50),
    purchase_year integer CHECK (purchase_year IS NULL OR purchase_year BETWEEN 1900 AND 2100),
    purchase_month integer CHECK (purchase_month IS NULL OR purchase_month BETWEEN 1 AND 12),
    lease_status_id integer REFERENCES quote.yes_no_unknown_options(id),
    purchase_condition_id integer REFERENCES quote.purchase_condition_options(id),
    tracking_system_status_id integer REFERENCES quote.yes_no_unknown_options(id),
    intensive_engraving_status_id integer REFERENCES quote.yes_no_unknown_options(id),
    modified_after_manufacturing_status_id integer REFERENCES quote.yes_no_unknown_options(id),
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote.quote_vehicle_usages
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_vehicle_id uuid NOT NULL UNIQUE REFERENCES quote.quote_vehicles(id) ON DELETE CASCADE,
    used_outside_quebec_status_id integer REFERENCES quote.yes_no_unknown_options(id),
    current_odometer_km integer CHECK (current_odometer_km IS NULL OR current_odometer_km >= 0),
    annual_distance_km integer CHECK (annual_distance_km IS NULL OR annual_distance_km >= 0),
    drive_for_business boolean,
    created_at_utc timestamptz NOT NULL DEFAULT now(),
    updated_at_utc timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS quote.quote_step_submissions
(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    quote_id uuid NOT NULL REFERENCES quote.quotes(id) ON DELETE CASCADE,
    step_code varchar(50) NOT NULL,
    submitted_at_utc timestamptz NOT NULL DEFAULT now(),
    payload_json jsonb NOT NULL
);

CREATE TABLE IF NOT EXISTS quote.quote_vehicle_drivers
(
    quote_vehicle_id uuid NOT NULL REFERENCES quote.quote_vehicles(id) ON DELETE CASCADE,
    quote_driver_id uuid NOT NULL REFERENCES quote.quote_drivers(id),
    is_primary_driver boolean NOT NULL DEFAULT false,
    PRIMARY KEY (quote_vehicle_id, quote_driver_id)
);

CREATE INDEX IF NOT EXISTS ix_quote_drivers_quote_id
    ON quote.quote_drivers(quote_id);

CREATE INDEX IF NOT EXISTS ix_quote_vehicles_quote_id
    ON quote.quote_vehicles(quote_id);

CREATE INDEX IF NOT EXISTS ix_quote_vehicles_manufacturer_id
    ON quote.quote_vehicles(manufacturer_id);

CREATE INDEX IF NOT EXISTS ix_quote_vehicles_vehicle_model_id
    ON quote.quote_vehicles(vehicle_model_id);

CREATE INDEX IF NOT EXISTS ix_quote_step_submissions_quote_id_submitted_at
    ON quote.quote_step_submissions(quote_id, submitted_at_utc);

CREATE UNIQUE INDEX IF NOT EXISTS ux_vehicle_models_manufacturer_year_code
    ON quote.vehicle_models(manufacturer_id, model_year, vehicle_code)
    WHERE vehicle_code IS NOT NULL;

ALTER TABLE quote.gender_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(100);

ALTER TABLE quote.marital_status_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(100);

ALTER TABLE quote.education_level_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(150);

ALTER TABLE quote.yes_no_unknown_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(100);

ALTER TABLE quote.purchase_condition_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(100);

ALTER TABLE quote.distance_options
    ADD COLUMN IF NOT EXISTS display_text_en varchar(50);

CREATE OR REPLACE FUNCTION quote.set_updated_at_utc()
RETURNS trigger AS $$
BEGIN
    NEW.updated_at_utc = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_quotes_set_updated_at ON quote.quotes;
CREATE TRIGGER trg_quotes_set_updated_at
BEFORE UPDATE ON quote.quotes
FOR EACH ROW EXECUTE FUNCTION quote.set_updated_at_utc();

DROP TRIGGER IF EXISTS trg_quote_drivers_set_updated_at ON quote.quote_drivers;
CREATE TRIGGER trg_quote_drivers_set_updated_at
BEFORE UPDATE ON quote.quote_drivers
FOR EACH ROW EXECUTE FUNCTION quote.set_updated_at_utc();

DROP TRIGGER IF EXISTS trg_quote_vehicles_set_updated_at ON quote.quote_vehicles;
CREATE TRIGGER trg_quote_vehicles_set_updated_at
BEFORE UPDATE ON quote.quote_vehicles
FOR EACH ROW EXECUTE FUNCTION quote.set_updated_at_utc();

DROP TRIGGER IF EXISTS trg_quote_vehicle_usages_set_updated_at ON quote.quote_vehicle_usages;
CREATE TRIGGER trg_quote_vehicle_usages_set_updated_at
BEFORE UPDATE ON quote.quote_vehicle_usages
FOR EACH ROW EXECUTE FUNCTION quote.set_updated_at_utc();

INSERT INTO quote.gender_options (code, display_text, display_text_en, sort_order)
VALUES
    ('Male', 'Homme', 'Male', 1),
    ('Female', 'Femme', 'Female', 2)
ON CONFLICT (code) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.marital_status_options (code, display_text, display_text_en, sort_order)
VALUES
    ('Single', 'Célibataire', 'Single', 1),
    ('Married', 'Marié', 'Married', 2),
    ('CommonLaw', 'Conjoint de fait', 'Common-law partner', 3),
    ('Divorced', 'Divorcé', 'Divorced', 4),
    ('Widowed', 'Veuf', 'Widowed', 5)
ON CONFLICT (code) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.education_level_options (code, display_text, display_text_en, sort_order)
VALUES
    ('None', 'Aucun', 'None', 1),
    ('Secondary', 'Secondaire', 'Secondary school', 2),
    ('CollegeDEC', 'Diplôme d''études collégiales (DEC)', 'College diploma (DEC)', 3),
    ('VocationalDEP', 'Diplôme d''études professionnelles (DEP)', 'Vocational diploma (DEP)', 4),
    ('UniversityBachelor', 'Université - Baccalauréat', 'University - Bachelor''s degree', 5),
    ('UniversityMaster', 'Université - Maîtrise', 'University - Master''s degree', 6),
    ('UniversityDoctorate', 'Université - Doctorat', 'University - Doctorate', 7)
ON CONFLICT (code) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.yes_no_unknown_options (code, display_text, display_text_en, sort_order)
VALUES
    ('Yes', 'Oui', 'Yes', 1),
    ('No', 'Non', 'No', 2),
    ('Unknown', 'Je ne sais pas', 'I do not know', 3)
ON CONFLICT (code) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.purchase_condition_options (code, display_text, display_text_en, sort_order)
VALUES
    ('New', 'Neuf', 'New', 1),
    ('Demo', 'Démo', 'Demo', 2),
    ('Used', 'Usagé', 'Used', 3)
ON CONFLICT (code) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.month_options (month_number, code, display_text, display_text_en, sort_order)
VALUES
    (1, '01', 'Janvier', 'January', 1),
    (2, '02', 'Février', 'February', 2),
    (3, '03', 'Mars', 'March', 3),
    (4, '04', 'Avril', 'April', 4),
    (5, '05', 'Mai', 'May', 5),
    (6, '06', 'Juin', 'June', 6),
    (7, '07', 'Juillet', 'July', 7),
    (8, '08', 'Août', 'August', 8),
    (9, '09', 'Septembre', 'September', 9),
    (10, '10', 'Octobre', 'October', 10),
    (11, '11', 'Novembre', 'November', 11),
    (12, '12', 'Décembre', 'December', 12)
ON CONFLICT (month_number) DO UPDATE SET
    code = EXCLUDED.code,
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;

INSERT INTO quote.vehicle_manufacturers (name)
VALUES
    ('HYUNDAI'),
    ('TOYOTA'),
    ('HONDA'),
    ('FORD'),
    ('CHEVROLET')
ON CONFLICT (name) DO UPDATE SET is_active = true;

WITH seeded_models(manufacturer_name, model_name, trim, vehicle_code) AS (
    VALUES
        ('HYUNDAI', 'IONIQ 5', 'PREFERRED LONG RANGE 4', 'IONIQ_5_PREFERRED_LONG_RANGE_4'),
        ('HYUNDAI', 'ELANTRA', NULL, 'ELANTRA'),
        ('HYUNDAI', 'TUCSON', NULL, 'TUCSON'),
        ('TOYOTA', 'COROLLA', NULL, 'COROLLA'),
        ('TOYOTA', 'RAV4', NULL, 'RAV4'),
        ('HONDA', 'CIVIC', NULL, 'CIVIC'),
        ('HONDA', 'CR-V', NULL, 'CR_V'),
        ('FORD', 'F-150', NULL, 'F_150'),
        ('FORD', 'ESCAPE', NULL, 'ESCAPE'),
        ('CHEVROLET', 'SILVERADO', NULL, 'SILVERADO'),
        ('CHEVROLET', 'EQUINOX', NULL, 'EQUINOX')
),
model_years(model_year) AS (
    SELECT generate_series(
        EXTRACT(YEAR FROM CURRENT_DATE)::integer + 1,
        EXTRACT(YEAR FROM CURRENT_DATE)::integer - 6,
        -1
    )
)
INSERT INTO quote.vehicle_models (manufacturer_id, model_year, model_name, trim, vehicle_code)
SELECT
    manufacturers.id,
    model_years.model_year,
    seeded_models.model_name,
    seeded_models.trim,
    seeded_models.vehicle_code
FROM seeded_models
JOIN quote.vehicle_manufacturers manufacturers
    ON manufacturers.name = seeded_models.manufacturer_name
CROSS JOIN model_years
ON CONFLICT ON CONSTRAINT uq_vehicle_models_model DO UPDATE SET
    vehicle_code = EXCLUDED.vehicle_code,
    is_active = true;

INSERT INTO quote.distance_options (kilometers, display_text, display_text_en, option_type, sort_order)
VALUES
    (10000, '10,000 km', '10,000 km', 'CurrentOdometer', 1),
    (30000, '30,000 km', '30,000 km', 'CurrentOdometer', 2),
    (50000, '50,000 km', '50,000 km', 'CurrentOdometer', 3),
    (75000, '75,000 km', '75,000 km', 'CurrentOdometer', 4),
    (100000, '100,000 km', '100,000 km', 'CurrentOdometer', 5),
    (5000, '5,000 km', '5,000 km', 'AnnualDistance', 1),
    (10000, '10,000 km', '10,000 km', 'AnnualDistance', 2),
    (15000, '15,000 km', '15,000 km', 'AnnualDistance', 3),
    (20000, '20,000 km', '20,000 km', 'AnnualDistance', 4),
    (25000, '25,000 km', '25,000 km', 'AnnualDistance', 5)
ON CONFLICT (kilometers, option_type) DO UPDATE SET
    display_text = EXCLUDED.display_text,
    display_text_en = EXCLUDED.display_text_en,
    sort_order = EXCLUDED.sort_order,
    is_active = true;
